### ISSUE TITLE
Feature request: Setting to hide Override Cover menu in roll dialog for players

### ISSUE THREAD

**Issue by Cuingamehtar** [reonZ/pf2e-perception#23]

**Comment by reonZ** [comment]
this is not a good idea, anyone who initiates a roll should be able to override it in case the module creates an incorrect result

if you end up in a situation were the module sets the cover as `x` and your GM tells you that it should actually be `y` due to special circumstances, then you should be able to apply `y` at that time

what is the problem with it showing up to players ?
