### ISSUE TITLE
[Feature] Validate Vision on Sneak

### ISSUE THREAD

**Issue by raymergames** [reonZ/pf2e-perception#28]
Love this module; one thing I would love tho is an option for the "Validate Vision" chat message to function with the Sneak action and the same kind of population that the current Hide function does:

### Hide Function auto populates/pops up + Validate Vision in message:
![Hide Ex](https://github.com/reonZ/pf2e-perception/assets/84054111/4d4dfccc-5e2a-48b8-847d-74511c9e7ccc)
Works perfectly and even with multiple targets.

### Sneak Function does not populate; does not pop up/is not handled; no validate vision button.
![sneak ex](https://github.com/reonZ/pf2e-perception/assets/84054111/6d0d1dca-dfce-493d-b3d3-c47cf3a6f82a)

- If Success - Populate Undetected
- If Failure - Populate Hidden
- If Crit Failure - Populate Observed.

_If there is concern of the Crit Failure and the situation of "well what if they're behind a wall and should be hidden instead of observed?" I wouldn't worry about this as if there's a proper wall; the creature won't be seen anyways with token vision._

Right now; everything but for Sneak is helped with automation and is the most common case the GM needs to manually validate without any population; it's also the most commonly used action when it comes to stealth.

**Comment by reonZ** [comment]
I tried to add support for sneak but the way it works is not sitting well with the core module, i could never implement it successfully.

And since sneak changes are done on a single token (the one that does the sneaking), it can easily be handled manually through the `Perception` menu of the module.

Lastly and even though i added support for `Create a Diversion` not too long ago, this module is not being worked on anymore beside the occasional fixes. v12 is around the corner and a lot of things are gonna change, the system is supposed to handle some of what the module currently does and i won't do anything until it is so.

**Comment by raymergames** [comment]
This makes sense with the team confirming some baseline features for token to token detection.

Thanks for the confirmation!
